In [1]:
import math
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
close_dataset = pd.read_csv("Predictions/Close Price Prediction.csv")
open_dataset = pd.read_csv("Predictions/Open Price Prediction.csv")
low_dataset = pd.read_csv("Predictions/Low Price Prediction.csv")
high_dataset = pd.read_csv("Predictions/High Price Prediction.csv")

In [19]:
length = len(close_dataset)

In [23]:
for index in range(length):
    c, o, l, h = close_dataset.at[index, "Close"], open_dataset.at[index, "Open"], low_dataset.at[index, "Low"], high_dataset.at[index, "High"]
    l = min(c, o, l, h)
    h = max(c, o, l, h)
    
    low_dataset.loc[index, "Low"] = l
    high_dataset.loc[index, "High"] = h

In [26]:
df = pd.concat([open_dataset, high_dataset, low_dataset, close_dataset], axis=1)
df.tail(20)

           Open       High        Low      Close
2313  230.99556  231.45380  230.04018  230.04018
2314  231.00122  231.43726  230.02988  230.02988
2315  230.97928  231.40758  229.99214  229.99214
2316  230.92430  231.36057  229.93149  229.93149
2317  230.95305  231.38630  229.95550  229.95550
2318  230.94061  231.37491  229.94392  229.94392
2319  231.00873  231.43938  230.01222  230.01222
2320  230.86769  231.32074  229.88654  229.88654
2321  230.87318  231.33075  229.89800  229.89800
2322  230.71930  231.18670  229.75221  229.75221
2323  230.73582  231.19736  229.75830  229.75830
2324  230.80956  231.24936  229.81334  229.81334
2325  231.00542  231.42519  229.99132  229.99132
2326  230.88542  231.34157  229.88867  229.88867
2327  230.92912  231.40187  229.95085  229.95085
2328  230.95435  231.41443  229.98439  229.98439
2329  230.78568  231.26785  229.82895  229.82895
2330  230.46996  230.99084  229.53477  229.53477
2331  230.33377  230.84792  229.38823  229.38823
2332  230.11935  230.63647  229.14973  229.14973

In [37]:
df.to_csv("Predictions\Overall_Predictions.csv")